prefixes:
  para1:
    primary: "2a05:1083:bef0::/44"
    secondary: "2a12:bec0:02c0::/44"
  para2:
    primary: "2a05:1083:bee0::/44"
    secondary: "2a05:dfc1:3c10::/44"
  ula: "fde4:5a50:1114::/48"
  third: "2a03:94e0:2496::/48"     # Podstawowa pula dla trzeciego prefixu
  alt-third: "2a05:dfc1:3ccc::/48"  # Alternatywna pula dla trzeciego prefixu

server:
  ipv4: "185.243.218.164"

api:
  key: "tb-sHj8Xp2qLkRtY7vZnM9wBcDfG3hJ6kL5mN8pQ7rS4tU2vW5xY9zA"
  listen: "127.0.0.1:8080"

database:
  max_connections: 10
  connection_lifetime: "1h"

security:
  rate_limit: 50 # Mbps
  blocked_ports:
    - 25   # SMTP
    - 465  # SMTP SSL
    - 587  # SMTP TLS
    - 2525 # SMTP Alternate
    - 110  # POP3
    - 995  # POP3 SSL
    - 143  # IMAP
    - 993  # IMAP SSL
